version: '3'
services:
  
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: ApplicationServer
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./ApplicationServer:/smart_meetings/application_server
      - /smart_meetings/application_server/node_modules
    ports:
      - "3000:3000"
    depends_on: 
      - db
      - py
    env_file:
      - .env
  py:
    build: python_server
    env_file:
      - .env
    ports:
      - "9999:9999"
    environment:
      - PYTHONUNBUFFERED=1
      # - py
    # network_mode: host
    # links:
    #   - python
# networks:
#   front:
#     a
